"""invites and suspension reason

Adds what a closed beta needs: single-use registration codes, and somewhere to
record why an account was suspended so the owner can be told.

Both are additive and nullable, so this applies to a live instance without
downtime and downgrades cleanly.

Revision ID: 153b1f097d11
Revises: 370a0065dc6a
Created: 2026-08-13 19:11:19.919280
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '153b1f097d11'
down_revision: str | None = '370a0065dc6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended_reason', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspended_reason')

    op.drop_table('invites')
    # ### end Alembic commands ###
